### ISSUE TITLE
issue al eliminar devices y vincularlo a google home

### ISSUE THREAD

**Issue by mangzz** [kikeelectronico/Homeware#18]
Originalmente existe un device que se llama **Bulb**

Cuando agregas mas dispositivos y posteriormente eliminas alguno de los ya existentes, por ejemplo el dispositivo **Bulb** en el **CMS** todo lo hace correcto, incluso en la base de datos, pero el problema sucede al quererlo vincular a **Google Home**, muestra mensaje: **Se produjo un error, vuelve a intentarlo**.

**Comment by kikeelectronico** [comment]
Released in https://github.com/kikeelectronico/Homeware/releases/tag/v0.6.1

Thanks @mangzz
