### ISSUE TITLE
Exampe Database error

### ISSUE THREAD

**Issue by jbenleo** [kikeelectronico/Homeware#19]
Wrong authorization_code value for 'light' id

https://github.com/kikeelectronico/Homeware/blob/dbc2f341f58bb1191f0c9847187bdde6b868f759/Database/database_example.json#L54

**Comment by kikeelectronico** [comment]
Solved. It will be available in the next release.

**Comment by kikeelectronico** [comment]
Released in https://github.com/kikeelectronico/Homeware/releases/tag/v0.6.1

Thanks @jbenleo
