### ISSUE TITLE
Al crear nuevo dispositivo, desaparecen los dispostivos creados y error en estado online

### ISSUE THREAD

**Issue by AHScerradura** [kikeelectronico/Homeware#32]
Hola, antes de nada gracias por tu trabajo.

He detectado varios errores que te paso a comentar.

1. Al crear un dispositivo nuevo existiendo ya otro, se borran todos los dispositivos de la página de devices, porque al salvar el dispositivo nuevo no se crea su contenido correspondiente en el status del json y esto provoca que no aparezca ninguno por error.
Solución: Al crear un segundo o más dispositivos añadir la cadena de status en el json.

2. Cuando un dispositivo se desconecta, aparece como conectado y google assistant lo considera tambien como conectado.

**Comment by kikeelectronico** [comment]
Hola AHScerradura,

1. No consigo reproducirlo. Supongo que tienes una versión antigua del CMS y en la actual v0.6.3 ya está corregido.

2. Para que la etiqueta _online_ funcione es necesario que tengas configurado la tarea _Cloud Scheduler_ desde la consola de _Google Cloud_.

Cierro la issue. No dudes en reabrirla si sigues teniendo problemas.

**Comment by kikeelectronico** [comment]
Reabro la issue. Parece que este error a vuelto.

**Comment by kikeelectronico** [comment]
Hola Carlos,

Estoy realizando la migración de Homeware-Firebase a Homeware-LAN.  Dejaré de dar soporte a Homeware-Firebase y esta issue no será resulta en Homeware-Firewbase. Te animo a que te migres a Homeware-LAN.
