### ISSUE TITLE
Error compilando light Example

### ISSUE THREAD

**Issue by javierrojas10** [kikeelectronico/Homeware#33]
`Archiving built core (caching) in: /var/folders/s0/f2ks3l2n2xbgb918k87cmnwh0000gn/T/arduino_cache_227059/core/core_esp8266_esp8266_generic_xtal_80,vt_flash,exception_legacy,ssl_all,ResetMethod_ck,CrystalFreq_26,FlashFreq_40,FlashMode_dio,eesz_512K64,led_2,sdk_nonosdk_190703,ip_lm2f,dbg_Disabled,lvl_None____,wipe_none,baud_115200_c86bf8242d0f2f343dbc82b3af86a07b.a
/Users/javorojas/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: libraries/Homeware/homeware.cpp.o: in function `Homeware::Homeware(char*, char*, BearSSL::WiFiClientSecure*)':
/Users/javorojas/Documents/Arduino/libraries/Homeware/homeware.cpp:3: multiple definition of `Homeware::Homeware(char*, char*, BearSSL::WiFiClientSecure*)'; sketch/homeware.cpp.o:sketch/homeware.cpp:3: first defined here
/Users/javorojas/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: libraries/Homeware/homeware.cpp.o: in function `Homeware::Homeware(char*, char*, BearSSL::WiFiClientSecure*)':
/Users/javorojas/Documents/Arduino/libraries/Homeware/homeware.cpp:3: multiple definition of `Homeware::Homeware(char*, char*, BearSSL::WiFiClientSecure*)'; sketch/homeware.cpp.o:sketch/homeware.cpp:3: first defined here
/Users/javorojas/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: libraries/Homeware/homeware.cpp.o: in function `Homeware::test()':
/Users/javorojas/Documents/Arduino/libraries/Homeware/homeware.cpp:26: multiple definition of `Homeware::test()'; sketch/homeware.cpp.o:sketch/homeware.cpp:26: first defined here
/Users/javorojas/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: libraries/Homeware/homeware.cpp.o: in function `Homeware::getToken(bool)':
/Users/javorojas/Documents/Arduino/libraries/Homeware/homeware.cpp:30: multiple definition of `Homeware::getToken(bool)'; sketch/homeware.cpp.o:sketch/homeware.cpp:30: first defined here
/Users/javorojas/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: libraries/Homeware/homeware.cpp.o: in function `Homeware::getJSON()':
/Users/javorojas/Documents/Arduino/libraries/Homeware/homeware.cpp:124: multiple definition of `Homeware::getJSON()'; sketch/homeware.cpp.o:sketch/homeware.cpp:124: first defined here
/Users/javorojas/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: libraries/Homeware/homeware.cpp.o: in function `Homeware::sendTrait(char*, char*, char*)':
/Users/javorojas/Documents/Arduino/libraries/Homeware/homeware.cpp:181: multiple definition of `Homeware::sendTrait(char*, char*, char*)'; sketch/homeware.cpp.o:sketch/homeware.cpp:181: first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compilando para la tarjeta Generic ESP8266 Module.`

Solo use el ejemplo y reemplazé los datos, también declare D0

`const byte D0 = 0;`

Porque me aparecía este error:
`/Users/javorojas/Documents/ARDUINO/luz-escritorio/luz-escritorio.ino: In function 'void setup()':
luz-escritorio:25: error: 'D0' was not declared in this scope
   pinMode(D0, OUTPUT);
           ^
/Users/javorojas/Documents/ARDUINO/luz-escritorio/luz-escritorio.ino: In function 'void loop()':
luz-escritorio:76: error: 'D0' was not declared in this scope
       if (state && !digitalRead(D0)){
                                 ^
exit status 1
'D0' was not declared in this scope`

Espero puedas ayudar, Saludos!

**Comment by javierrojas10** [comment]
Uso la versión 2.6.2 de ESP8266

**Comment by javierrojas10** [comment]
Mala mía, había abierto el archivo de HomeWare.cpp y por eso no me compilaba, está todo ok. Pero  lo de declarar el D0 si errar una error.

**Comment by kikeelectronico** [comment]
D0 es una declaración del core del ESP8266. Supongo que en la definición de la placa que estés usando no está definido.

**Comment by javierrojas10** [comment]
Así parece, pero declarandolo me funcionó solo que luego se sobrepasó el
límite de firebase y tuve que usar otro sistema para vincular a google
home, porque ya no me pude conectar más.
