### ISSUE TITLE
¿cómo agregar un dispositivo que actualmente ya tengo en mi google home?

### ISSUE THREAD

**Issue by leifermendez** [kikeelectronico/Homeware#36]
Hola excelente proyecto, felicitaciones!. Actualmente ya lo tengo desplegado y todo el ejemplo me funciona bien. Mi pregunta tengo actualmente un swith marca tp link que ya tengo integrado en mi google home existe alguna forma de poder sincronizar estos dispositivos hacia el homeware o no se puede ?

**Comment by kikeelectronico** [comment]
No se pueden integrar dispositivos de fabricantes como tp-link a Homeware, tendrías que vincularlo con Google Home usando tu cuenta en tp-link.

Estoy realizando la migración de Homeware-Firebase a Homeware-LAN. Te animo a que te migres a Homeware-LAN.
