### ISSUE TITLE
Firebase recursos agotados

### ISSUE THREAD

**Issue by carlosovejas17** [kikeelectronico/Homeware#37]
Buenos días,
Lo primero gracias por tu trabajo y enhorabuena por la aplicación Homeware
Llevo días intentando hacer funcionar Homeware con los pasos que explicas en Youtube y tras conseguirlo y hacerlo funcionar correctamente, dejó de hacerlo y en Firebase aparece este error:
![Firebase](https://user-images.githubusercontent.com/59613771/72511401-67005880-384b-11ea-9c90-21454d5a37c9.JPG)
Parece que he consumido todos los recursos que Firebase presta gratuitamente, pero no lo entiendo ya que solo, encendí y apague un led varias veces para probarlo.

Espero que sea algún error conocido, muchas gracias por tu ayuda 
Un saludo

**Comment by kikeelectronico** [comment]
¿Puedes mirar que plan de Firebase tienes? 

Esto es uno de los problemas que tiene usar este servicio. Estoy trabajando en otra versión de Homeware para Raspberry Pi y así poder autoalojarlo.

**Comment by carlosovejas17** [comment]
Tengo el gratuito, solo me da dos opciones. 
No se cual es el coste del de pago por eso no he cambiado de plan 
La version para autoalojarlo es una buenisima idea
Un saludo

Edito:
Por aclararlo, tengo la versión Spark, y me da opción a cambiar a Blaze.
Un saludo

**Comment by kikeelectronico** [comment]
Hola Carlos,

Estoy realizando la migración de Homeware-Firebase a Homeware-LAN. Uno de los motivos es el uso de recursos. Dejaré de dar soporte a Homeware-Firebase. Te animo a que te migres a Homeware-LAN.
