### ISSUE TITLE
Integrar comando de Fetch 

### ISSUE THREAD

**Issue by lucasdellasantina** [kikeelectronico/Homeware#38]
Integrar ejecucion de comando en fetch o bash para automatizar porcesos, para podes scriptear procesos

**Comment by kikeelectronico** [comment]
Voy a dejar de dar soporte a Homeware-Firebase. FIrebase no es la plataforma adecuada para este tipo de aplicaciones.

Te animo a que pases a Homeware-LAN. Aquí es posible que integre algo similar a lo que comentas. Si no te importa, escríbeme desde http://contacto.rinconingenieril.es/ y me cuentas en más detalle en que idea estas pensando.
