### ISSUE TITLE
Soporte para esta version VS Homeware LAN

### ISSUE THREAD

**Issue by metalbass** [kikeelectronico/Homeware#41]
Hola! Estaba empezando a montar un servidor de Firebase y me preguntaba cual es el futuro de esta versión de Homeware.

¿Hay algún sitio donde leer el porque de esta decisión? Quizá esas razones me hacen montarlo el servidor en una raspberry como recomienda Homeware LAN, no lo sé. 😋

**Comment by kikeelectronico** [comment]
Voy a dejar de dar soporte a Homeware-Firebase. FIrebase no es la plataforma adecuada para este tipo de aplicaciones. Estoy trabajando en la documentación que explica los motivos del cambio.

Te animo a que pases a Homeware-LAN.
