### ISSUE TITLE
Instrucciones incorrectas en api?

### ISSUE THREAD

**Issue by alejandro-anv** [kikeelectronico/Homeware#8]
He estado intentando seguri las instrucciones de la API pero me encuentro con que al llegar al paso de "Go to Backend service under Advanced Options in the left side menu.", no veo un menú de advanced options por ningún lado. Tampoco nada de Backend. 
Las opciones que veo son:
Invication
Actions
Account linking

Me magino que desde que se escribieron esas instrucciones habrá cambiado algo la página de configuración, pero en realidad el último cambio del documento fue hace 16 días así que no se...

**Comment by kikeelectronico** [comment]
Ya lo he actualizado en _master_ y en este [release](https://github.com/kikeelectronico/Homeware/releases/tag/v0.4).

Google cambio la consola de _Actions on Google_ hace muy poco.

También puedes seguir las instrucciones en [https://www.rinconingenieril.es/homeware-api-google-home/](https://www.rinconingenieril.es/homeware-api-google-home/).

Hay un paso que no está en las instrucciones debido a que aún tengo que validarlo. Es posible que tengas que cambiar la configuración de facturación de Firebase de Spark a Blaze.
